setTimeout(() => {
    try {
        what;
    } catch(e) {
        console.log("에러 발생!");
    }
}, 1000);