try {
    setTimeout(() => {
        what;
    }, 1000);
} catch (e) {
    console.log("에러 발생!");
}